### ISSUE TITLE
New icon design

### ISSUE THREAD

**Issue by aberus** [ayamadori/OpenWithMaps#1]
Suggestion for new icon design:

![fileextension1 targetsize-336](https://user-images.githubusercontent.com/2404410/36865708-989708bc-1d90-11e8-800f-7e99ace1be99.png)

**Comment by ayamadori** [comment]
Do you mean that this app should use the same icon as Windows Maps app?
It's impossible because it does NOT comply with Windows Store Policy.

**Comment by aberus** [comment]
Just wanted to suggest that icon could look more beautiful and consistent with other icons.

This is how currently looks in windows explorer:
![image](https://user-images.githubusercontent.com/2404410/37252142-833a1e94-251c-11e8-8e74-0a62cdd8a371.png)

**Comment by ayamadori** [comment]
I understood your issue.
I used the icon that you made in the latest update. Thank you!

**Comment by aberus** [comment]
No problem, I'm glad I could help.
Very useful app. 5 stars 👍
